### ISSUE TITLE
Chybějící panely u zpěvníku

### ISSUE THREAD

**Issue by michaeldojcar** [glowspace/proscholy-phone#28]
Prostředí: Android 10
(Na iPhone 11 se mi bug nepodařilo vyvolat, protože nemám u písně systémové tlačítko zpět),
 
Jde o to, že appka si zapamatuje skrytí horní a dolní lišty u písně 
a pak tento stav přenese i do seznamu papírového zpěvníku, kde by horní a dolní navigace měla být vždy.

**Kroky k vyvolání bugu:**
1. otevřu libovolnou píseň
2. ťuknu do textu a zmizí panely
3. kliknu na HW/SW tlačítko zpět a vyjedu z písně
4. otevřu libovolný papírový zpěvník a je to (navigace je pryč :D)

**Comment by Paprikadobi** [comment]
Bude v pohodě, když prostě to tlačítko zpět zablokuju?

**Comment by michaeldojcar** [comment]
Obávám se, že bychom tím uživateli dost znepříjemnili práci. Androidí user se pomocí toho právě dost často pohybuje a tady čeká, že ho vrátí zpět z písně, což by se mělo zachovat. Jenom se v současném stavu nevyresetuje skrytí těch panelů.

**Comment by michaeldojcar** [comment]
Ideál by byl kdyby to fungovalo jak teď, jen by u zpěvníku nezmizely ty panely.

**Comment by Paprikadobi** [comment]
Aha, on se vlastně na androidu skrývá je horní bar, protože ten spodní tam není defaultně, že? Tak to nebude problém.

**Comment by michaeldojcar** [comment]
Díky za vražedně rychlý fix. :-)

**Comment by michaeldojcar** [comment]
Teď se to chová korektně, ale zmizel dolní bar u seznamu konkr. zpěvníku. (Android 10, MIUI 12.0.4)

**Comment by michaeldojcar** [comment]
![Screenshot_2021-11-19-22-05-43-362_jozkar mladez](https://user-images.githubusercontent.com/1665018/142691685-54a3a8ff-69d9-4a1a-9f70-59c1efbb6d7b.jpg)

**Comment by Paprikadobi** [comment]
No ten dolní bar na androidu nebyl nikdy. Podle toho co jsem dříve zjišťoval, tak je to takhle správné chování u material widgetů na androidu. Kdyžtak to zkusím někdy předělat podle nějakého tutoriálu, ale asi ne v blízké době, protože toho bude potřeba předělat docela dost a na to bych teď neměl čas.
